* Copyright

GNU Guix --- Functional package management for GNU
Copyright © 2020 Ryan Prior <rprior@protonmail.com>

#+html: <details>
#+html: <summary>Copyright info</summary>
This file is not part of GNU Guix.

GNU Guix is free software; you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.

GNU Guix is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with GNU
Guix. If not, see <http://www.gnu.org/licenses/>.
#+html: </details>

* Packages
** visidata

VisiData is an interactive multitool for tabular data. It combines the clarity
of a spreadsheet, the efficiency of the terminal, and the power of Python, into
a lightweight utility which can handle millions of rows.

- name :: visidata
- version :: 2.2.1
- home-page :: https://www.visidata.org/
- synopsis :: Terminal spreadsheet multitool for discovering and arranging data
- license :: gpl3

*** Source
#+begin_src scheme
  (origin
    (method url-fetch)
    (uri (pypi-uri "visidata" version))
    (sha256
     (base32
      "181klx7223q6a600k9iqxrfxpq5w73h1g2ks1cfsnmlv7i6s9v9f")))
#+end_src

*** Build system
This package uses the ~python-build-system~.

**** inputs
- python-dateutil
- python-fonttools
- python-h5py
- python-lxml
- python-openpyxl
- python-pandas
- python-psycopg2
- python-pyyaml
- python-requests
- python-xlrd

**** arguments
***** ~#:phases~
#+begin_src scheme
  (modify-phases %standard-phases
    (replace 'check
      (lambda* (#:key tests? #:allow-other-keys)
        (when tests? (invoke "pytest"))
        #t)))
#+end_src

* Guile Modules
#+begin_src scheme
  (define-module (gnu packages visidata)
    #:use-module (gnu packages check)
    #:use-module (gnu packages time)
    #:use-module (gnu packages python-web)
    #:use-module (gnu packages python-xyz)
    #:use-module (gnu packages xml)
    #:use-module (guix build-system python)
    #:use-module (guix build utils)
    #:use-module (guix download)
    #:use-module ((guix licenses) #:prefix license:)
    #:use-module (guix packages))
#+end_src
