* Copyright

GNU Guix --- Functional package management for GNU
Copyright © 2020 Ryan Prior <rprior@protonmail.com>

This file is not part of GNU Guix.

GNU Guix is free software; you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.

GNU Guix is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with GNU
Guix. If not, see <http://www.gnu.org/licenses/>.

* Packages
** visidata

VisiData is an interactive multitool for tabular data. It combines the clarity
of a spreadsheet, the efficiency of the terminal, and the power of Python, into
a lightweight utility which can handle millions of rows.

- name :: visidata
- version :: 1.5.2
- home-page :: https://www.visidata.org/
- synopsis :: Terminal spreadsheet multitool for discovering and arranging data
- license ::
  + license:gpl3
  + license:expat
    :COMMENT:
    (visidata/vdtui.py)
    :END:

*** Source
**** origin
:PROPERTIES:
:method:   url-fetch
:base32-sha256-hash: 10adfyn4gkisvciqawgh2lakkhhnjjxiyp7mzbgcwkq1b3sigpf1
:END:

- uri ::
#+name: uri
#+begin_src guile
(pypi-uri "visidata" version)
#+end_src

*** Build system
:PROPERTIES:
:type: python-build-system
:END:

**** inputs
| package name     | symbol           |
|------------------+------------------|
| python-dateutil  | python-dateutil  |
| python-fonttools | python-fonttools |
| python-h5py      | python-h5py      |
| python-lxml      | python-lxml      |
| python-openpyxl  | python-openpyxl  |
| python-pandas    | python-pandas    |
| python-psycopg2  | python-psycopg2  |
| python-pyyaml    | python-pyyaml    |
| python-requests  | python-requests  |
| python-xlrd      | python-xlrd      |

**** arguments

#+name: #:tests?
#+begin_src guile
#f
#+end_src
* Guile Modules
** gnu
*** packages
- visidata
- databases
- python-science
- python-web
- python-xyz
- time
- xml
** guix
*** build-system
- python
*** licenses
:PROPERTIES:
:prefix: license:
:END:
*** packages

